version: '3.8'

services:
  # Redis 서비스 정의
  redis:
    image: redis:7-alpine  # 가볍고 공식적인 Redis 이미지
    container_name: log_redis
    ports:
      - "6379:6379" # 호스트와 컨테이너의 포트 연결 (디버깅용)
    command: redis-server --save 60 1 --loglevel warning # 60초마다 1개 이상의 키가 변경되면 디스크에 저장

  # MySQL 서비스 정의
  mysql:
    image: mysql:8.0
    container_name: log_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=log_summer
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # 로그 컨슈머 애플리케이션 서비스 정의
  log-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log_consumer
    ports:
      - "8081:8081"
    # 애플리케이션이 Redis와 MySQL에 의존함을 명시 (먼저 뜨도록)
    depends_on:
      - redis
      - mysql
    # 애플리케이션이 사용할 환경 변수 (Redis 및 MySQL 호스트 정보)
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/log_summer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

volumes:
  mysql_data: