version: '3.8'

services:
  # Redis 서비스 정의
  redis:
    image: redis:7-alpine  # 가볍고 공식적인 Redis 이미지
    container_name: log_redis
    ports:
      - "6379:6379" # 호스트와 컨테이너의 포트 연결 (디버깅용)
    command: redis-server --save 60 1 --loglevel warning # 60초마다 1개 이상의 키가 변경되면 디스크에 저장

  # 기존 애플리케이션 서비스 정의
  app:
    build: . # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드
    container_name: log_summer_be
    ports:
      - "8080:8080"
    # 애플리케이션이 Redis에 의존함을 명시 (Redis가 먼저 뜨도록)
    depends_on:
      - redis
    # 애플리케이션이 사용할 환경 변수 (Redis 호스트 정보)
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
